import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// FlutterFire compatible options holder.
///
/// This repo does not store Firebase credentials in source control.
/// For web builds, provide Firebase config via `--dart-define` (or a
/// `--dart-define-from-file` json).
class DefaultFirebaseOptions {
  static FirebaseOptions get web {
  return const FirebaseOptions(
      apiKey: String.fromEnvironment('FIREBASE_API_KEY', defaultValue: ''),
      appId: String.fromEnvironment('FIREBASE_APP_ID', defaultValue: ''),
      messagingSenderId:
        String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: ''),
      projectId:
        String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: ''),
      authDomain:
        String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: ''),
      storageBucket:
        String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: ''),
      measurementId:
        String.fromEnvironment('FIREBASE_MEASUREMENT_ID', defaultValue: ''),
    );
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web in this repo. '
      'For mobile, use google-services.json / GoogleService-Info.plist or '
      'extend this file with platform options generated by FlutterFire.',
    );
  }
}
